version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            - sudo yum install libmysqlclient-dev
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
