version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - sudo yum makecache --refresh
            - sudo yum update -y
            - sudo yum -y install pkgconfig
            - pip install --upgrade pip
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
