version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - sudo apt install pkg-config
            - sudo apt-get install python3-dev default-libmysqlclient-dev build-essential
            - pip install --upgrade pip
            - pip install -r requirements.txt
    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
