"""
Django settings for resort project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cafusabcdefghiacfdeysaczdsfoapqwsbbbbbbbbbbbsaaaaaaaaaaa'  # this is the dummy key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hideaway',
    'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'resort.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resort.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mygeneric',
        'USER': 'admin',
        'PASSWORD': '16121996',
        'HOST':'mygenericdb.chwlezgyi7rm.eu-west-1.rds.amazonaws.com',
        'PORT':'3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'

AWS_ACCESS_KEY_ID="ASIATUYJP7SUNN62OIWU"
AWS_SECRET_ACCESS_KEY="RXX4GBo5DuTX+yHPQm6lQumY37MkcyDpvO9jm2If"
AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEKr//////////wEaCXVzLWVhc3QtMSJGMEQCIEwCFiBpy3addWw6j2rtk/WGLxs1U6KJ0uRFPJXw6KJnAiBhrynIz/FdMlEVRFCL2HGjkVFH/qsCj8P0Tr/ggTq+Byr7AwgTEAMaDDI1MDczODYzNzk5MiIM8X28gXqjilM6NzAAKtgDYWTFWPi6XhOs8j4fni4Hjkz2HeN9TNKWBKnk+WsMMozoCXglaz1jPLfkLsdw5QyNihp9z27xYRg2cs8X+/sPPtGNvNHwQTk6BX3HfWblmi7JdWPMBbsBFR9peEtLPt0IIAsk+BJnuSPNJy62BSjw9RuS8G2t4ZPm/+E5LpfoOoIrkNuP2iBVNsIUOiY4IJMX40PlchCPiuStYWdh5sDuIGwmq9kepM/ZSz1moK46ICf0lDOn0xkqwvIbXI690YPSD4L7CG+eLF0bJ6I5KDfykwo9OykwAJHnnO+o/XF0LK3Wj2gcQC5BKDg6i8vB3PVWvidhAdliLtPs0xAumVLetL+Dj3gVErG1XOrjdIrhTmMnpScFUfWAZxHUv+9xnelPSJoG2MgZfuocQiv+c/tqfvMXYCjGAUZB9cQ23RK7gyn0Es1J4bq9TpiJe5V3etb5UOez11T2yUj3lvtXFS4sAprHmWWYV/s5oD1Pi7V1J9xTEw9RmtFoH2mNLhXfyItnMYDjjGX+56pTWMr/+WFCZNgYSa5E5me0AJ/DnS0owA+CmeAct9Pj8km6iCIReI1MJIjsFPx9ag4ebmC6CitZZAmcT+OVmZmac8iUWwCFl43kL25EwqXrBjD+3aarBjqnASkNDi9svai7xUhO7LDWmk1XA7cdq75reB0rI+bwZ0SYgTg7KjHpnDrGSnLGwBEqYY7JBdQ/99XpYmPUpIc/wTNbUG66+C4wMk5HhzGFoRAWmuoZySZW7Q/XgKoS5YGb9ycQpDpyLy1nbd4Cjo9HPw9zOZ+kggp0bOU/yhE80/fKWcoRHDn69FZgGAax1wLFN5iLAjo719u6gF4okYMIogLhWbwSOAw/"
